name = "meu-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Configuração para importar arquivos HTML como texto
[rules]
[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true
